#!/usr/bin/env python
# -*- coding: utf-8 -*-

TURN_SPEED = 5
MAX_SPEED = 5
HEARTBEAT_INTERVAL = 5

GAME_STEP_MIN_TIME = 0.015
NEAR_RADIUS = 20

DEBUG = False

ROTATE_TURNING = 'TURNING'
ROTATE_FLIP_VERTICAL = 'FLIP_VERTICAL'
ROTATE_FLIP_HORIZONTAL = 'FLIP_HORIZONTAL'
ROTATE_FLIP_BOTH = 'FLIP_BOTH'
ROTATE_NO_TURN = 'NO_TURN'