#!/usr/bin/env python
# -*- coding: utf-8 -*-

TURN_SPEED = 5
MAX_SPEED = 5
HEARTBEAT_INTERVAL = 5

GAME_STEP_MIN_TIME = 0.015
NEAR_RADIUS = 20

DEBUG = False

TURNING = 'TURNING'
FLIP_VERTICAL = 'FLIP_VERTICAL'
FLIP_HORIZONTAL = 'FLIP_HORIZONTAL'
FLIP_BOTH = 'FLIP_BOTH'
NO_TURN = 'NO_TURN'